15 create UI home page
chilleric/franchise-sys-frontend pull request #21
Opened 2022-12-31 16:02 UTC by jayha14

2023-01-03 06:14 UTC, ericchentch commented on components/card/cards-with-title/CardsWithTitle.tsx
> +export const CardsWithTitle = ({ title, children }: ICardsWithTitle) => {
find another solution for title of card

2023-01-03 06:14 UTC, ericchentch requested changes
Check comments

2023-01-03 06:16 UTC, jayha14 commented on components/card/cards-with-title/CardsWithTitle.tsx
> +export const CardsWithTitle = ({ title, children }: ICardsWithTitle) => {
yes, sir!

2023-01-04 01:44 UTC, ericchentch approved these changes
LGMR

2023-01-04 01:47 UTC, merged